# Generated by Django 2.2.4 on 2020-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='trial', max_length=10),
        ),
    ]
